// Generated by Dagger (https://dagger.dev).
package br.com.adenilson.gist.domain.mapper;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GistListMapperImpl_Factory implements Factory<GistListMapperImpl> {
  @Override
  public GistListMapperImpl get() {
    return newInstance();
  }

  public static GistListMapperImpl_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static GistListMapperImpl newInstance() {
    return new GistListMapperImpl();
  }

  private static final class InstanceHolder {
    private static final GistListMapperImpl_Factory INSTANCE = new GistListMapperImpl_Factory();
  }
}
